[firebase]
apiKey = "AIzaSyCYEZ2AWi0gtntVFhbpLytTVzWF78R00DU"
authDomain = "terrop-cfb71.firebaseapp.com"
databaseURL = "https://terrop-cfb71-default-rtdb.firebaseio.com"
projectId = "terrop-cfb71"
storageBucket = "terrop-cfb71.appspot.com"
messagingSenderId = "161712926661"
appId = "1:161712926661:web:a5f4d9c108f7413291a5ac"
measurementId = "G-80KS5MG0LY"
